import java.util.HashMap;
import java.util.Map;

public class Day2 {
    private static Map<Character, Integer> CHAR_VALUE_MAP = new HashMap<>();

    static {
        CHAR_VALUE_MAP.put('X', 1);
        CHAR_VALUE_MAP.put('Y', 2);
        CHAR_VALUE_MAP.put('Z', 3);
    }

    public static void main(String[] args) {
        test("A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "B X\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y");
    }

    private static void test(String input) {
        Utils.log("Day2 -- total score for given strategy");
        int total = computeTotal(input);
    }

    private static int computeTotal(String input) {
        String[] lines = input.split("\n");
        int total = 0;
        for (String line : lines) {
            total += computeResult(line.charAt(0), line.charAt(2));
        }
        return total;
    }

    private static int computeResult(char a, char b) {
        return -1;
//        int total = CHAR_VALUE_MAP.get(b);
////        switch (b) {
////            case 'X':
////                switch (a) {
////                    case 'A':
////                }
////                break;
////            case 'Y':
////                break;
////            case 'Z':
////                break;
////        }
//
//        if ((a == 'A' && b == 'X') || (a == 'B' && b == 'Y') || (a == 'C' && b == 'Z')) {
//            return total;
//        } else if (a == 'A')
//            return total;
    }
}
